# Inserts a blank line between shell prompts
add_newline = true
right_format = """$time$username$hostname"""

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "
vicmd_symbol = "[â®¬](bold yellow)"

[container]
disabled = true

[directory]
truncation_length = 4
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ğŸŒ± "
truncation_length = 4
truncation_symbol = "â€¦"

[memory_usage]
disabled = false
style = "bold dimmed yellow"

[username]
format = "[$user@]($style)"
style_user = "bold dimmed green"

[hostname]
format = "[$hostname]($style)"
style = "bold dimmed green"

[time]
disabled = false
format = 'ğŸ•™[ $time ]($style)'
